config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("food_app.urls", namespace="author-polls")),
]

food_app/urls.py
from django.contrib import admin
from django.urls import path
import food_app.views

app_name="food_app"
urlpatterns = [
    path('', food_app.views.index, name="home" ),
    # path for details basd on id
    path('details/<int:item_id>', food_app.views.details, name="details"),
    # path for edit based on id
    path('edit/<int:item_id>', food_app.views.edit, name="edit"),
    path('add_item', food_app.views.add_item, name="add_item")
]

admin_pages/models.py
from django.db import models

# Create your models here.
class admin_model(models.Model):
    role = models.CharField(max_length=70),
    

food_app/models.py
from django.db import models

# Create your models here.
# a model for storeing a food that can be ordered
class Food_Item(models.Model):
    def __str__(self) -> str:
        return self.item_name
    item_name = models.CharField(max_length=200)
    item_description = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_type =  models.CharField(max_length=40)
    item_image = models.URLField(default='')

front_end_food_app/models.py
from django.db import models

# Create your models here.

food_app/views.py
#django
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

# models
from food_app.models import Food_Item


# Create your views here.
def index(request):
    food_list = Food_Item.objects.all()
    template = 'index.html'
    # creates a dictonary of food_items
    context = {
        'food_list' : food_list
    }
    # one way to render templates
    # return HttpResponse(template.render(context, request))
    return render(request, template, context)

def details(request, item_id):
    template = 'details.html'
    # creates a dictonary of food_items

    item_id = Food_Item.objects.get(pk= item_id)
    print(item_id)
    context = {
        'food_item': item_id
    }
    return render(request, template, context)

def add_item(request):
    template = 'add_item.html'
    return render(request, template)

def edit(request, item_id):
    template = 'edit_item.html'
    # creates a dictonary of food_items

    item_id = Food_Item.objects.get(id = item_id)
    print(item_id)
    context = {
        'food_item': item_id
    }
    return render(request, template, context)

front_end_food_app/views.py
from django.shortcuts import render

# Create your views here.

admin_pages/templates/admin.html
{% extends "layout.html" %}
{% block title %}Admin{% endblock %}
{% block content %}
Admin
{% endblock %}

admin_pages/templates/new_user.html
{% extends "layout.html" %}
{% block title %}New User{% endblock %}
{% block content %}

{% endblock %}

admin_pages/templates/view_users.html
{% extends "layout.html" %}
{% block title %}Add Item{% endblock %}
{% block content %}
add item
{% endblock %}

food_app/templates/add_item.html
{% extends "layout.html" %}
{% block title %}Add Item{% endblock %}
{% block content %}

    <h1>Add new item</h1>
    <form id="form_formated">
        <div class="input_field">
            <label  class="form_label" for="inputname">Name</label>
            <input class="form_input" type="text" id="inputname">
        </div>
        <div class="input_field">
            <label class="form_label" for="TextareaDescription">Description</label>
            <textarea class="form_input" id="TextareaDescription" rows="3"></textarea>
        </div>
        <div class="input_field">
            <label class="form_label"  for="inputnumber">Price</label>
            <input class="form_input" type="number" id="inputnumber">
        </div>
        <div class="input_field">
            <label class="form_label"  for="inputname">Type</label>
            <input class="form_input" type="text" id="inputname">
        </div>
        <div class="input_field" class="input_field">
            <label class="form_label" for="inputurl">Image link</label>
            <input class="form_input" type="url" id="inputurl">
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
    </form>

{% endblock %}

food_app/templates/details.html
{% extends "layout.html" %}
{% block title %}details{% endblock %}
{% block content %}
    <div class="details_box"> 
        <img src={{ food_item.item_image }} width="200px" height="200px">
        <div class="details">
            <div>
            {{ food_item.item_name }}
            </div>
            <div>
            {{ food_item.item_description }} 
            </div>
            <div>
            {{ food_item.item_price }}
            </div>
        </div>
    </div>
    <div class="button_box">
        <a href="{% url 'food_app:edit' item_id=food_item.id %}" class="btn btn-primary" type="button">Edit</a>
        <button class="btn btn-primary" type="button">Delete</button>
    </div>
{% endblock %}

food_app/templates/edit_item.html
{% extends "layout.html" %}
{% block title %}Update item{% endblock %}
{% block content %}
<h1>Update item</h1>
<form id="form_formated">
    <div class="input_field">
        <label  class="form_label" for="inputname">Name</label>
        <input class="form_input" type="text" id="inputname">
    </div>
    <div class="input_field">
        <label class="form_label" for="TextareaDescription">Description</label>
        <textarea class="form_input" id="TextareaDescription" rows="3"></textarea>
    </div>
    <div class="input_field">
        <label class="form_label"  for="inputnumber">Price</label>
        <input class="form_input" type="number" id="inputnumber">
    </div>
    <div class="input_field">
        <label class="form_label"  for="inputname">Type</label>
        <input class="form_input" type="text" id="inputname">
    </div>
    <div class="input_field" class="input_field">
        <label class="form_label" for="inputurl">Image link</label>
        <input class="form_input" type="url" id="inputurl">
    </div>
    <button type="submit" class="btn btn-primary">Sign in</button>
</form>
{% endblock %}

food_app/templates/index.html
{% extends "layout.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
{% for food_item in food_list %}
    <a href = "{% url 'food_app:details' item_id=food_item.id %}" class="details_box"> 
        <img src={{ food_item.item_image }} width="200px" height="200px">
        <div class="details">
            <div>
            {{ food_item.item_name }}
            </div>
            <div>
            {{ food_item.item_description }} 
            </div>
            <div>
            {{ food_item.item_price }}
            </div>
        </div>
    </a>
{% endfor %}
{% endblock %}

food_app/templates/layout.html
{% load static %}
<!doctype html>
<html>
  <head>
    {% block head %}
        <title>{% block title %}{% endblock %} - Food App</title>
        <link rel="icon" type="image/x-icon" href="{% static 'Python icon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body class="container container-sm">
    {% block header %}
    <header class="site-header sticky-top py-1">
        <nav class="navbar navbar-expand-lg dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'food_app:home' %}">Food App</a>
                    <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'food_app:add_item' %}">Add item</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Update Account</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="#">Reset Password</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Login</a>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Logout</a>
                            </li>
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    {% endblock %}
    <div id="content" class="flexed-container">{% block content %}{% endblock %}</div>
    <div id="footer">
      {% block footer %}
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
      &copy; Copyright 2023 by <a href="#">ECleaver</a>.
      {% endblock %}
    </div>
  </body>
</html>

food_app/templates/new_user.html
{% extends "layout.html" %}
{% block title %}New User{% endblock %}
{% block content %}

{% endblock %}

food_app/templates/view_users.html
{% extends "layout.html" %}
{% block title %}Add Item{% endblock %}
{% block content %}
add item
{% endblock %}

front_end_food_app/templates/index.html
{% extends "layout.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
Home Page
{% endblock %}

front_end_food_app/templates/layout.html
<!doctype html>
<html>
  <head>
    {% block head %}
        <title>{% block title %}{% endblock %} - Food App</title>
        <link rel="icon" type="image/x-icon" href="static/Python icon.ico">
        <link rel="stylesheet" type="text/css" href="static/style.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body class="container container-sm">
    {% block header %}
    <header class="site-header sticky-top py-1">
        <nav class="navbar navbar-expand-lg dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Home</a>
                    <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            <a class="nav-link" href="/work">Work</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="/Blog">Blog</a>
                            <li class="nav-item">
                            <a class="nav-link" href="/contact">Contact</a>
                            </li>
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    {% endblock %}
    <div id="content" class="flexed-container">{% block content %}{% endblock %}</div>
    <div id="footer">
      {% block footer %}
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
      &copy; Copyright 2023 by <a href="#">ECleaver</a>.
      {% endblock %}
    </div>
  </body>
</html>

front_end_food_app/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}
Login
{% endblock %}

front_end_food_app/templates/logout.html
{% extends "layout.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
Logged out
{% endblock %}

front_end_food_app/templates/order_item.html
{% extends "layout.html" %}
{% block title %}Order item{% endblock %}
{% block content %}
Order item
{% endblock %}

front_end_food_app/templates/ordered.html
{% extends "layout.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
Ordered
{% endblock %}

front_end_food_app/templates/register.html
{% extends "layout.html" %}
{% block title %}Register{% endblock %}
{% block content %}

{% endblock %}

front_end_food_app/templates/reset_password.html
{% extends "layout.html" %}
{% block title %}Password Reset{% endblock %}
{% block content %}
Password Reset
{% endblock %}